In [3]:
import os
import pathlib

import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import tensorflow as tf

from tensorflow.keras import layers
from tensorflow.keras import models
from IPython import display

import pandas as pd

# Set the seed value for experiment reproducibility.
seed = 42
tf.random.set_seed(seed)
np.random.seed(seed)

In [4]:
DATASET_PATH = 'data/mini_speech_commands'

data_dir = pathlib.Path(DATASET_PATH)
if not data_dir.exists():
  tf.keras.utils.get_file(
      'mini_speech_commands.zip',
      origin="http://storage.googleapis.com/download.tensorflow.org/data/mini_speech_commands.zip",
      extract=True,
      cache_dir='.', cache_subdir='data')

In [5]:
commands = np.array(tf.io.gfile.listdir(str(data_dir)))
commands = commands[(commands != 'README.md') & (commands != '.DS_Store')]
print('Commands:', commands)

Commands: ['down' 'go' 'left' 'no' 'right' 'stop' 'up' 'yes']


In [6]:
train_ds, val_ds = tf.keras.utils.audio_dataset_from_directory(
    directory=data_dir,
    batch_size=64,
    validation_split=0.2,
    seed=0,
    output_sequence_length=16000,
    subset='both')

label_names = np.array(train_ds.class_names)
print("label names:", label_names)

Found 8000 files belonging to 8 classes.
Using 6400 files for training.
Using 1600 files for validation.
label names: ['down' 'go' 'left' 'no' 'right' 'stop' 'up' 'yes']


In [23]:
# ---- IMPROVE ----#
from IPython.display import clear_output
ind = 0
new_train_ds = np.array((6400, 16001, 1))
for x in train_ds:
    for sm in x[0]:
        print(sm)
    for smn in x[1]:
        new_train_ds[ind][16001] = smn

tf.Tensor(
[[ 0.00756836]
 [ 0.00515747]
 [ 0.00357056]
 ...
 [-0.01681519]
 [-0.01278687]
 [-0.01358032]], shape=(16000, 1), dtype=float32)
tf.Tensor(
[[0.0007019 ]
 [0.00112915]
 [0.00100708]
 ...
 [0.        ]
 [0.        ]
 [0.        ]], shape=(16000, 1), dtype=float32)
tf.Tensor(
[[-0.00112915]
 [-0.00100708]
 [-0.00210571]
 ...
 [-0.0015564 ]
 [-0.00140381]
 [-0.00247192]], shape=(16000, 1), dtype=float32)
tf.Tensor(
[[-3.0517578e-05]
 [-9.1552734e-05]
 [-1.2207031e-04]
 ...
 [ 2.1362305e-04]
 [ 2.4414062e-04]
 [ 1.5258789e-04]], shape=(16000, 1), dtype=float32)
tf.Tensor(
[[-0.00131226]
 [-0.00213623]
 [-0.00231934]
 ...
 [-0.00079346]
 [-0.0012207 ]
 [-0.00170898]], shape=(16000, 1), dtype=float32)
tf.Tensor(
[[ 0.0010376 ]
 [ 0.00097656]
 [ 0.00094604]
 ...
 [-0.00183105]
 [-0.00158691]
 [-0.00152588]], shape=(16000, 1), dtype=float32)
tf.Tensor(
[[0.00061035]
 [0.00079346]
 [0.00076294]
 ...
 [0.00091553]
 [0.0010376 ]
 [0.00085449]], shape=(16000, 1), dtype=float32)
tf.Tens

TypeError: 'numpy.int32' object does not support item assignment

In [69]:
# Commands: ['down' 'go' 'left' 'no' 'right' 'stop' 'up' 'yes']
# indeces : [ 0      1    2      3    4       5      6    7]
# so we want to remove 1 3 and 7
for i in range(64*16000, 64*16000+64):
    if(new_train_ds[i] in {1, 3, 7}):
        np.delete(new_train_ds)


1.0
1.0
1.0
7.0
7.0
3.0
3.0
3.0
1.0
3.0
3.0
7.0
7.0
3.0
3.0
7.0
1.0
3.0
1.0
1.0
